# -*- coding: utf-8 -*-
"""Untitled.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-fS_v51D8mC6EEuaHT6hmFC4zMJoG1xJ
"""


import streamlit as st
from PyPDF2 import PdfReader
import re
import os
from gtts import gTTS

def download_text(text):
    file_name = "extracted_text.txt"
    path = os.path.join(os.path.expanduser("~"), "Downloads", file_name)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    st.success("Text file has been downloaded.")
    

def download_audio(text):
    audio = gTTS(text)
    audio_file_name = "extracted_text.mp3"
    audio_path = os.path.join(os.path.expanduser("~"), "Downloads", audio_file_name)
    audio.save(audio_path)
    st.success("Audio file has been downloaded.")
    

def main():
    uploaded_file = st.file_uploader("Choose a file", type=["pdf"])
    
    
    if uploaded_file is not None:
        st.write("file uploaded ")
        pdf = PdfReader(uploaded_file)
        num_pages = len(pdf.pages)
        text = []
        for i in range(num_pages):
            page = pdf.pages[i]
            text.append(page.extract_text())
        text = "".join(text)
        text = re.sub(r'[^\w\s]', '', text)
        st.write("Extracted text from the pdf")
        st.write(text)
        download_text_button = st.button("Download Text", key="download_text")
        if download_text_button:
            download_text(text)

        download_audio_button = st.button("Download Audio", key="download_audio")
        if download_audio_button:
            download_audio(text)  

            

if __name__ == "__main__":
    main()





